#!/bin/sh
# When configured within MPICH via PAC_CONFIG_SUBDIR, this file will be sourced
# by the top-level configure.  This lets us propagate shell variable changes
# back upstream.

CPPFLAGS="  -I/mnt/exports/shared/home/ccuser/scc2020/practice/mpi_intro/mvapich2/mvapich2-2.3.4/src/mpl/include -I/mnt/exports/shared/home/ccuser/scc2020/practice/mpi_intro/mvapich2/mvapich2-2.3.4/src/mpl/include -I/mnt/exports/shared/home/ccuser/scc2020/practice/mpi_intro/mvapich2/mvapich2-2.3.4/src/openpa/src -I/mnt/exports/shared/home/ccuser/scc2020/practice/mpi_intro/mvapich2/mvapich2-2.3.4/src/openpa/src -D_REENTRANT -I/mnt/exports/shared/home/ccuser/scc2020/practice/mpi_intro/mvapich2/mvapich2-2.3.4/src/mpi/romio/include"
WRAPPER_LIBS="$WRAPPER_LIBS "
